openapi: 3.0.0
info:
  title: Shopify Inventory API
  version: 1.0.0
paths:
  /getInventory:
    get:
      summary: Retrieve Shopify Inventory Levels
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - variant_id: 123456789
                  inventory_quantity: 50
                  available_quantity: 45
                  updated_at: "2024-01-23T12:34:56Z"

  /updateInventory/{variantId}:
    put:
      summary: Update Shopify Inventory Level
      parameters:
        - in: path
          name: variantId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              inventory_item:
                quantity: 60
      responses:
        '200':
          description: Inventory level updated successfully
          content:
            application/json:
              example:
                variant_id: 123456789
                inventory_quantity: 60
                available_quantity: 55
                updated_at: "2024-01-23T13:45:00Z"

  /getStockItem/{variantId}:
    get:
      summary: Retrieve Shopify Stock Item
      parameters:
        - in: path
          name: variantId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                variant_id: 123456789
                cost: 20.0
                created_at: "2024-01-23T10:00:00Z"
                updated_at: "2024-01-23T10:30:00Z"
